-- +goose Up
INSERT INTO business_categories (slug, name, description, display_order) VALUES
  ('attractions-and-heritage', 'Attractions and heritage', 'Monuments, heritage sites, temples, viewpoints, public attractions, and photo spots.', 85),
  ('shopping-and-markets', 'Shopping and markets', 'Malls, local markets, flea markets, night markets, and shopping districts.', 86),
  ('wellness-and-self-care', 'Wellness and self care', 'Spas, salons, yoga, meditation, massage, and recovery-focused experiences.', 87),
  ('learning-and-hobbies', 'Learning and hobbies', 'Classes, workshops, hobby studios, creative sessions, and skill-based activities.', 88)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  display_order = EXCLUDED.display_order,
  active = true,
  updated_at = CURRENT_TIMESTAMP;

UPDATE business_categories
SET display_order = 150,
    updated_at = CURRENT_TIMESTAMP
WHERE slug = 'other-local-service';

INSERT INTO business_subcategories (category_id, slug, name, display_order)
SELECT c.id, item.slug, item.name, item.display_order
FROM business_categories c
JOIN (
  VALUES
    ('street-food', 'kebab-tandoor', 'Kebab / Tandoor', 110),
    ('street-food', 'pav-bhaji', 'Pav Bhaji', 120),
    ('street-food', 'dosa-idli', 'Dosa / Idli', 130),
    ('street-food', 'sweets', 'Sweets', 140),
    ('street-food', 'juice-shakes', 'Juice / Shakes', 150),
    ('street-food', 'paratha', 'Paratha', 160),
    ('street-food', 'biryani-rice', 'Biryani / Rice', 170),
    ('street-food', 'regional-snacks', 'Regional Snacks', 180),

    ('restaurant-or-cafe', 'family-restaurant', 'Family Restaurant', 80),
    ('restaurant-or-cafe', 'casual-dining', 'Casual Dining', 90),
    ('restaurant-or-cafe', 'buffet', 'Buffet', 100),
    ('restaurant-or-cafe', 'fast-food', 'Fast Food', 110),
    ('restaurant-or-cafe', 'food-court', 'Food Court', 120),
    ('restaurant-or-cafe', 'cloud-kitchen', 'Cloud Kitchen', 130),
    ('restaurant-or-cafe', 'bar-and-grill', 'Bar and Grill', 140),

    ('fun-and-entertainment', 'pool-snooker', 'Pool / Snooker', 80),
    ('fun-and-entertainment', 'board-games', 'Board Games', 90),
    ('fun-and-entertainment', 'laser-tag', 'Laser Tag', 100),
    ('fun-and-entertainment', 'kids-play-area', 'Kids Play Area', 110),
    ('fun-and-entertainment', 'amusement-park', 'Amusement Park', 120),

    ('adventure', 'trekking', 'Trekking', 60),
    ('adventure', 'camping', 'Camping', 70),
    ('adventure', 'zipline', 'Zipline', 80),
    ('adventure', 'rafting', 'Rafting', 90),
    ('adventure', 'cycling-trail', 'Cycling Trail', 100),
    ('adventure', 'offbeat-outdoor', 'Offbeat Outdoor Activity', 110),

    ('nightlife', 'rooftop-bar', 'Rooftop Bar', 50),
    ('nightlife', 'brewery', 'Brewery', 60),
    ('nightlife', 'dj-night', 'DJ Night', 70),
    ('nightlife', 'sports-screening', 'Sports Screening', 80),
    ('nightlife', 'cocktail-bar', 'Cocktail Bar', 90),
    ('nightlife', 'dance-floor', 'Dance Floor', 100),

    ('culture-and-events', 'art-gallery', 'Art Gallery', 60),
    ('culture-and-events', 'exhibition', 'Exhibition', 70),
    ('culture-and-events', 'stand-up-comedy', 'Stand-up Comedy', 80),
    ('culture-and-events', 'open-mic', 'Open Mic', 90),
    ('culture-and-events', 'heritage-walk', 'Heritage Walk', 100),
    ('culture-and-events', 'book-event', 'Book Event', 110),

    ('sports-and-fitness', 'gym', 'Gym', 50),
    ('sports-and-fitness', 'yoga', 'Yoga', 60),
    ('sports-and-fitness', 'skating', 'Skating', 70),
    ('sports-and-fitness', 'tennis', 'Tennis', 80),
    ('sports-and-fitness', 'basketball', 'Basketball', 90),
    ('sports-and-fitness', 'martial-arts', 'Martial Arts', 100),
    ('sports-and-fitness', 'dance-fitness', 'Dance Fitness', 110),

    ('relax-and-explore', 'picnic-spot', 'Picnic Spot', 50),
    ('relax-and-explore', 'viewpoint', 'Viewpoint', 60),
    ('relax-and-explore', 'riverside', 'Riverside', 70),
    ('relax-and-explore', 'scenic-drive', 'Scenic Drive', 80),
    ('relax-and-explore', 'meditation-place', 'Meditation Place', 90),

    ('travel-or-transport', 'city-tour', 'City Tour', 40),
    ('travel-or-transport', 'cab-rental', 'Cab Rental', 50),
    ('travel-or-transport', 'bike-rental', 'Bike Rental', 60),
    ('travel-or-transport', 'bus-operator', 'Bus Operator', 70),
    ('travel-or-transport', 'homestay', 'Homestay', 80),
    ('travel-or-transport', 'campsite', 'Campsite', 90),
    ('travel-or-transport', 'travel-agent', 'Travel Agent', 100),

    ('attractions-and-heritage', 'monument', 'Monument', 10),
    ('attractions-and-heritage', 'heritage-site', 'Heritage Site', 20),
    ('attractions-and-heritage', 'temple', 'Temple / Religious Place', 30),
    ('attractions-and-heritage', 'photo-spot', 'Photo Spot', 40),
    ('attractions-and-heritage', 'zoo', 'Zoo', 50),
    ('attractions-and-heritage', 'aquarium', 'Aquarium', 60),
    ('attractions-and-heritage', 'science-center', 'Science Center', 70),
    ('attractions-and-heritage', 'public-attraction', 'Public Attraction', 80),

    ('shopping-and-markets', 'mall', 'Mall', 10),
    ('shopping-and-markets', 'local-market', 'Local Market', 20),
    ('shopping-and-markets', 'flea-market', 'Flea Market', 30),
    ('shopping-and-markets', 'night-market', 'Night Market', 40),
    ('shopping-and-markets', 'handicrafts', 'Handicrafts', 50),
    ('shopping-and-markets', 'books', 'Books', 60),
    ('shopping-and-markets', 'fashion-market', 'Fashion Market', 70),
    ('shopping-and-markets', 'electronics-market', 'Electronics Market', 80),

    ('wellness-and-self-care', 'spa', 'Spa', 10),
    ('wellness-and-self-care', 'salon', 'Salon', 20),
    ('wellness-and-self-care', 'massage', 'Massage', 30),
    ('wellness-and-self-care', 'yoga-studio', 'Yoga Studio', 40),
    ('wellness-and-self-care', 'meditation', 'Meditation', 50),
    ('wellness-and-self-care', 'ayurveda', 'Ayurveda', 60),
    ('wellness-and-self-care', 'fitness-recovery', 'Fitness Recovery', 70),
    ('wellness-and-self-care', 'nail-studio', 'Nail Studio', 80),

    ('learning-and-hobbies', 'art-class', 'Art Class', 10),
    ('learning-and-hobbies', 'dance-class', 'Dance Class', 20),
    ('learning-and-hobbies', 'music-class', 'Music Class', 30),
    ('learning-and-hobbies', 'cooking-class', 'Cooking Class', 40),
    ('learning-and-hobbies', 'photography-walk', 'Photography Walk', 50),
    ('learning-and-hobbies', 'pottery', 'Pottery', 60),
    ('learning-and-hobbies', 'language-class', 'Language Class', 70),
    ('learning-and-hobbies', 'maker-workshop', 'Maker Workshop', 80),

    ('other-local-service', 'event-planner', 'Event Planner', 10),
    ('other-local-service', 'photographer', 'Photographer', 20),
    ('other-local-service', 'party-decorator', 'Party Decorator', 30),
    ('other-local-service', 'equipment-rental', 'Equipment Rental', 40),
    ('other-local-service', 'local-guide', 'Local Guide', 50),
    ('other-local-service', 'community-space', 'Community Space', 60),
    ('other-local-service', 'pet-service', 'Pet Service', 70),
    ('other-local-service', 'other-experience', 'Other Experience', 80)
) AS item(category_slug, slug, name, display_order) ON item.category_slug = c.slug
ON CONFLICT (category_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  display_order = EXCLUDED.display_order,
  active = true,
  updated_at = CURRENT_TIMESTAMP;

-- +goose Down
DELETE FROM business_subcategories s
USING business_categories c
WHERE s.category_id = c.id
  AND (c.slug, s.slug) IN (
    ('street-food', 'kebab-tandoor'),
    ('street-food', 'pav-bhaji'),
    ('street-food', 'dosa-idli'),
    ('street-food', 'sweets'),
    ('street-food', 'juice-shakes'),
    ('street-food', 'paratha'),
    ('street-food', 'biryani-rice'),
    ('street-food', 'regional-snacks'),
    ('restaurant-or-cafe', 'family-restaurant'),
    ('restaurant-or-cafe', 'casual-dining'),
    ('restaurant-or-cafe', 'buffet'),
    ('restaurant-or-cafe', 'fast-food'),
    ('restaurant-or-cafe', 'food-court'),
    ('restaurant-or-cafe', 'cloud-kitchen'),
    ('restaurant-or-cafe', 'bar-and-grill'),
    ('fun-and-entertainment', 'pool-snooker'),
    ('fun-and-entertainment', 'board-games'),
    ('fun-and-entertainment', 'laser-tag'),
    ('fun-and-entertainment', 'kids-play-area'),
    ('fun-and-entertainment', 'amusement-park'),
    ('adventure', 'trekking'),
    ('adventure', 'camping'),
    ('adventure', 'zipline'),
    ('adventure', 'rafting'),
    ('adventure', 'cycling-trail'),
    ('adventure', 'offbeat-outdoor'),
    ('nightlife', 'rooftop-bar'),
    ('nightlife', 'brewery'),
    ('nightlife', 'dj-night'),
    ('nightlife', 'sports-screening'),
    ('nightlife', 'cocktail-bar'),
    ('nightlife', 'dance-floor'),
    ('culture-and-events', 'art-gallery'),
    ('culture-and-events', 'exhibition'),
    ('culture-and-events', 'stand-up-comedy'),
    ('culture-and-events', 'open-mic'),
    ('culture-and-events', 'heritage-walk'),
    ('culture-and-events', 'book-event'),
    ('sports-and-fitness', 'gym'),
    ('sports-and-fitness', 'yoga'),
    ('sports-and-fitness', 'skating'),
    ('sports-and-fitness', 'tennis'),
    ('sports-and-fitness', 'basketball'),
    ('sports-and-fitness', 'martial-arts'),
    ('sports-and-fitness', 'dance-fitness'),
    ('relax-and-explore', 'picnic-spot'),
    ('relax-and-explore', 'viewpoint'),
    ('relax-and-explore', 'riverside'),
    ('relax-and-explore', 'scenic-drive'),
    ('relax-and-explore', 'meditation-place'),
    ('travel-or-transport', 'city-tour'),
    ('travel-or-transport', 'cab-rental'),
    ('travel-or-transport', 'bike-rental'),
    ('travel-or-transport', 'bus-operator'),
    ('travel-or-transport', 'homestay'),
    ('travel-or-transport', 'campsite'),
    ('travel-or-transport', 'travel-agent'),
    ('attractions-and-heritage', 'monument'),
    ('attractions-and-heritage', 'heritage-site'),
    ('attractions-and-heritage', 'temple'),
    ('attractions-and-heritage', 'photo-spot'),
    ('attractions-and-heritage', 'zoo'),
    ('attractions-and-heritage', 'aquarium'),
    ('attractions-and-heritage', 'science-center'),
    ('attractions-and-heritage', 'public-attraction'),
    ('shopping-and-markets', 'mall'),
    ('shopping-and-markets', 'local-market'),
    ('shopping-and-markets', 'flea-market'),
    ('shopping-and-markets', 'night-market'),
    ('shopping-and-markets', 'handicrafts'),
    ('shopping-and-markets', 'books'),
    ('shopping-and-markets', 'fashion-market'),
    ('shopping-and-markets', 'electronics-market'),
    ('wellness-and-self-care', 'spa'),
    ('wellness-and-self-care', 'salon'),
    ('wellness-and-self-care', 'massage'),
    ('wellness-and-self-care', 'yoga-studio'),
    ('wellness-and-self-care', 'meditation'),
    ('wellness-and-self-care', 'ayurveda'),
    ('wellness-and-self-care', 'fitness-recovery'),
    ('wellness-and-self-care', 'nail-studio'),
    ('learning-and-hobbies', 'art-class'),
    ('learning-and-hobbies', 'dance-class'),
    ('learning-and-hobbies', 'music-class'),
    ('learning-and-hobbies', 'cooking-class'),
    ('learning-and-hobbies', 'photography-walk'),
    ('learning-and-hobbies', 'pottery'),
    ('learning-and-hobbies', 'language-class'),
    ('learning-and-hobbies', 'maker-workshop'),
    ('other-local-service', 'event-planner'),
    ('other-local-service', 'photographer'),
    ('other-local-service', 'party-decorator'),
    ('other-local-service', 'equipment-rental'),
    ('other-local-service', 'local-guide'),
    ('other-local-service', 'community-space'),
    ('other-local-service', 'pet-service'),
    ('other-local-service', 'other-experience')
  );

DELETE FROM business_categories
WHERE slug IN (
  'attractions-and-heritage',
  'shopping-and-markets',
  'wellness-and-self-care',
  'learning-and-hobbies'
);

UPDATE business_categories
SET display_order = 100,
    updated_at = CURRENT_TIMESTAMP
WHERE slug = 'other-local-service';
